avance bookValidation y createBook
EcommerceProyect/BookStore-E-commerce pull request #8
Opened 2023-12-15 15:50 UTC by MaximilianoDienes

2023-12-15 16:10 UTC, NPirizSmith approved these changes

2023-12-15 16:12 UTC, chrivel14 approved these changes

2023-12-15 16:26 UTC, LuisaBarrios05 approved these changes

2023-12-15 16:37 UTC, 4zin approved these changes

2023-12-15 18:59 UTC, NPirizSmith approved these changes

2023-12-15 19:00 UTC, NPirizSmith approved these changes

2023-12-15 19:12 UTC, nicolaselozano approved these changes

2023-12-15 19:58 UTC, GenaroCura approved these changes

2023-12-17 18:17 UTC, nicolaselozano requested changes
Resolver los conflictos con la rama

2023-12-17 20:21 UTC, nicolaselozano approved these changes

2023-12-17 20:55 UTC, merged